# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_app', '0003_auto_20180412_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='blog',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs_app.Blog'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='telephone',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='用户手机号'),
        ),
    ]
