# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_app', '0004_auto_20180412_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_count',
            field=models.ImageField(default=0, upload_to='', verbose_name='文章评论数'),
        ),
        migrations.AddField(
            model_name='article',
            name='down_count',
            field=models.ImageField(default=0, upload_to='', verbose_name='文章踩灭数'),
        ),
        migrations.AddField(
            model_name='article',
            name='up_count',
            field=models.ImageField(default=0, upload_to='', verbose_name='文章点赞数'),
        ),
    ]
