# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_app', '0005_auto_20180416_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='文章发布时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论发表时间'),
        ),
    ]
