# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_app', '0007_auto_20180416_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs_app.Category', verbose_name='文章所属分类'),
        ),
    ]
